version: 2

before:
  hooks:
    - go mod tidy

builds:
  - ldflags:
      - -s -w -X github.com/m-hammad-faisal/envguard/cmd.version={{.Version}}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64

archives:
  - formats:
      - tar.gz
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        formats:
          - zip

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^chore:"
      - "^style:"
      - "^test:"
      - Merge pull request
      - Merge branch

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
