package cmd

import (
	"bufio"
	"encoding/json"
	"fmt"
	"os"
	"strings"

	"github.com/spf13/cobra"
)

// Config is shared across the cmd package (scan.go reads replacement_template).
type Config struct {
	ReplacementTemplate string `json:"replacement_template"`
}

var initCmd = &cobra.Command{
	Use:   "init",
	Short: "Initialize EnvGuard in the current repository",
	RunE:  runInit,
}

func init() {
	rootCmd.AddCommand(initCmd)
}

func runInit(cmd *cobra.Command, args []string) error {
	if err := os.MkdirAll(".envguard", 0755); err != nil {
		return fmt.Errorf("failed to create .envguard directory: %w", err)
	}
	fmt.Println("✓ Created .envguard/")

	if err := installHook(); err != nil {
		return fmt.Errorf("failed to install pre-commit hook: %w", err)
	}

	template := detectFramework()
	config := Config{ReplacementTemplate: template}
	configData, err := json.MarshalIndent(config, "", "  ")
	if err != nil {
		return fmt.Errorf("failed to marshal config: %w", err)
	}
	if err := os.WriteFile(".envguard/config.json", configData, 0644); err != nil {
		return fmt.Errorf("failed to write config.json: %w", err)
	}
	fmt.Printf("✓ Wrote .envguard/config.json (template: %s)\n", template)

	if err := generateStarterEnv(); err != nil {
		return fmt.Errorf("failed to generate .env: %w", err)
	}

	if err := ensureGitignore(); err != nil {
		return fmt.Errorf("failed to update .gitignore: %w", err)
	}

	fmt.Println("\n✓ EnvGuard initialized. Run 'envguard push' to encrypt your .env.")
	return nil
}

// installHook is shared with pull.go.
func installHook() error {
	hookPath := ".git/hooks/pre-commit"
	const hookTrigger = "envguard scan"
	const hookBlock = "\n# EnvGuard: prevent hardcoded secrets\n" + hookTrigger + "\n"

	if err := os.MkdirAll(".git/hooks", 0755); err != nil {
		return fmt.Errorf("failed to create hooks directory: %w", err)
	}

	existing, err := os.ReadFile(hookPath)
	if err == nil {
		// File exists — check for duplicate before appending
		if strings.Contains(string(existing), hookTrigger) {
			fmt.Println("✓ Pre-commit hook already contains envguard scan (skipped)")
			return nil
		}
		f, err := os.OpenFile(hookPath, os.O_APPEND|os.O_WRONLY, 0755)
		if err != nil {
			return fmt.Errorf("failed to open existing hook for appending: %w", err)
		}
		defer f.Close()
		if _, err := f.WriteString(hookBlock); err != nil {
			return err
		}
		fmt.Println("✓ Appended envguard scan to existing pre-commit hook")
		return nil
	}

	// No existing hook — write a clean one
	content := "#!/bin/sh" + hookBlock
	if err := os.WriteFile(hookPath, []byte(content), 0755); err != nil {
		return fmt.Errorf("failed to write pre-commit hook: %w", err)
	}
	fmt.Println("✓ Installed pre-commit hook")
	return nil
}

func detectFramework() string {
	type rule struct {
		file     string
		contains string
		template string
	}

	rules := []rule{
		{"package.json", `"next"`, `process.env.{{KEY}}`},
		{"package.json", "", `process.env.{{KEY}}`},
		{"go.mod", "", `os.Getenv("{{KEY}}")`},
		{"requirements.txt", "", `os.environ["{{KEY}}"]`},
		{"Pipfile", "", `os.environ["{{KEY}}"]`},
		{"pyproject.toml", "", `os.environ["{{KEY}}"]`},
	}

	for _, r := range rules {
		if _, err := os.Stat(r.file); err != nil {
			continue
		}
		if r.contains == "" {
			return r.template
		}
		data, err := os.ReadFile(r.file)
		if err == nil && strings.Contains(string(data), r.contains) {
			return r.template
		}
	}

	// Fallback: ask the user
	fmt.Print("Could not detect framework. Enter your env var reference syntax (e.g., process.env.{{KEY}}): ")
	reader := bufio.NewReader(os.Stdin)
	input, _ := reader.ReadString('\n')
	return strings.TrimSpace(input)
}

func generateStarterEnv() error {
	if _, err := os.Stat(".env"); err == nil {
		fmt.Println("✓ .env already exists (skipped)")
		return nil
	}

	var lines []string
	lines = append(lines, "# Generated by EnvGuard — fill in values and run 'envguard push'")

	if data, err := os.ReadFile("package.json"); err == nil {
		content := string(data)
		if strings.Contains(content, `"next"`) {
			lines = append(lines, "\n# Next.js",
				"NEXT_PUBLIC_APP_URL=",
				"NEXTAUTH_SECRET=",
				"NEXTAUTH_URL=",
			)
		}
		if strings.Contains(content, "prisma") {
			lines = append(lines, "\n# Prisma", "DATABASE_URL=")
		}
		if strings.Contains(content, "@supabase") {
			lines = append(lines, "\n# Supabase",
				"NEXT_PUBLIC_SUPABASE_URL=",
				"NEXT_PUBLIC_SUPABASE_ANON_KEY=",
				"SUPABASE_SERVICE_ROLE_KEY=",
			)
		}
	}

	if _, err := os.Stat("go.mod"); err == nil {
		lines = append(lines, "\n# Go application", "PORT=8080", "DATABASE_URL=")
	}

	if _, err := os.Stat("requirements.txt"); err == nil {
		lines = append(lines, "\n# Python application", "DATABASE_URL=", "SECRET_KEY=")
	}

	content := strings.Join(lines, "\n") + "\n"
	if err := os.WriteFile(".env", []byte(content), 0600); err != nil {
		return err
	}
	fmt.Println("✓ Generated starter .env")
	return nil
}

func ensureGitignore() error {
	data, err := os.ReadFile(".gitignore")
	if err == nil && strings.Contains(string(data), ".env") {
		return nil
	}
	f, err := os.OpenFile(".gitignore", os.O_APPEND|os.O_CREATE|os.O_WRONLY, 0644)
	if err != nil {
		return err
	}
	defer f.Close()
	_, err = f.WriteString("\n# EnvGuard\n.env\n")
	if err != nil {
		return err
	}
	fmt.Println("✓ Added .env to .gitignore")
	return nil
}
